#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable not set."
    exit 1
fi

filename=$(basename -- "$PYFILE")
extension="${filename##*.}"
filename="${filename%.*}"
output_filename="$filename.pyc"

echo "Compiling $PYFILE ..."
python3 -m py_compile "$PYFILE"

if [ $? -eq 0 ]; then
    echo "Compilation successful. Output filename: $output_filename"
else
    echo "Compilation failed."
    exit 1
fi
